#!/bin/bash
# Instruksi Setup Git dan Push ke GitHub

echo "=== SETUP GIT MANUAL ==="
echo ""
echo "1. Download Git dari: https://git-scm.com/download/win"
echo "2. Install dengan default settings"
echo "3. Restart PowerShell/CMD setelah install"
echo ""
echo "=== SETELAH GIT TERINSTALL, JALANKAN ==="
echo ""
echo "cd C:\\xampp\\htdocs\\p12"
echo ""
echo "# Konfigurasi git (sekali saja)"
echo "git config --global user.name 'Your Name'"
echo "git config --global user.email 'your.email@example.com'"
echo ""
echo "# Inisialisasi repo"
echo "git init"
echo "git add ."
echo "git commit -m 'first commit'"
echo "git branch -M main"
echo "git remote add origin https://github.com/kelompok2-pemrograman-bergerak-ti22e/pertemuan12.git"
echo "git push -u origin main"
echo ""
echo "=== JIKA AD PASSWORD ==="
echo "GitHub sudah tidak support password auth simple."
echo "Gunakan GitHub Personal Access Token atau SSH Key"
echo ""
echo "Lihat: https://github.com/settings/tokens"
